services:
  ollama-conttainer:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  streamlit-app:
    image: makishima/playdeas-streamlit:0.1
    ports:
      - 8501:8501